### PR TITLE
 Replace drawio PDF export with drawio File -> Print action #288

### PR DESCRIPTION
**Pull request by Farcasut**
Updated the code to rename the Print button to export pdf and removed the original export as pdf button

### CODE REVIEW

**Review by ChiuchiuSorin — APPROVED** [review]

**Comment by oanalavinia** [comment]
Hi! Please update the associated ticket to mention what is different after this change
For example, the fact that now the PDF export it's not in the `Export as -> PDF` menu anymore.

Also, I suppose the (now) export modal still mentions the print action (see below)
image
Could something be done for updating this?

**Comment by Farcasut** [comment]
> Hi! Please update the associated ticket to mention what is different after this change For example, the fact that now the PDF export it's not in the `Export as -> PDF` menu anymore.
> 
> Also, I suppose the (now) export modal still mentions the print action (see below) image Could something be done for updating this?

Hi! While I can override the mxClient.get method to change "print" to "export," this might mislead users. The button opens a new window, similar to pressing `CTRL+P`, and its behavior depends on whether a printer is connected. If a printer is connected, the default action is to print the document, otherwise, it saves it as a PDF. Keeping the label as "print" is likely better, as it prompts users to review the new window carefully and reduces the risk of accidentally printing instead of saving the document as a PDF.

**Comment by oanalavinia** [comment]
Ok, this is an important aspect that should have been mentioned 

In this case, the button should probably say `Print / Export as PDF`, since both actions can be possible. Also, all of this should be added in the documentation (and on the issue), in order to mention when one or the other can be achieved.
It's not necessarily nice to have a button that does both, but we shouldn't indeed lose the print action

**Comment by Farcasut** [comment]
> Ok, this is an important aspect that should have been mentioned
> 
> In this case, the button should probably say `Print / Export as PDF`, since both actions can be possible. Also, all of this should be added in the documentation (and on the issue), in order to mention when one or the other can be achieved. Also, is there a way to add a title for this button? It's not necessarily nice to have a button that does both, but we shouldn't indeed lose the print action

Instead of modifying the modal, wouldn’t it be better to change the name of the menu button? For example, instead of just "Export PDF," it could say "Export PDF or PRINT." This way, users can quickly identify the section, and we can update the documentation once the store is working again to mention that the print action opens a new window where users must choose whether to print the page or download the PDF. Wdyt?

**Comment by oanalavinia** [comment]
> In this case, the button should probably say `Print / Export as PDF`

That what I was saying here, that the button name should be changed, not the modal title. And I'd go for the `Print / Export as PDF` name

> Also, is there a way to add a title for this button?

Here I was talking about a title for the button (the one that is displayed on hover)

So yes, the modal title should remain as it is now

**Comment by Farcasut** [comment]
> Here I was talking about a title for the button (the one that is displayed on hover)

Thank you for the clarification, and sorry for the misunderstanding. I'm not sure if I can add a title in a straightforward way, but I will check. If it's possible, I will add it

**Comment by oanalavinia** [comment]
Ok, sounds good. Thanks!

**Pull request merged**
